// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDxtJbbOmNIKKnN_7jsMrxfA5sWv8UXZk',
    appId: '1:890970742539:web:2a5df1aaad41a512b24c0e',
    messagingSenderId: '890970742539',
    projectId: 'help4unotification',
    authDomain: 'help4unotification.firebaseapp.com',
    storageBucket: 'help4unotification.firebasestorage.app',
    measurementId: 'G-NLHKJKCME5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdYXbSnjd5FJOvltK47hwQy-EtkdOUNg',
    appId: '1:890970742539:android:f6ee150c5f275c18b24c0e',
    messagingSenderId: '890970742539',
    projectId: 'help4unotification',
    storageBucket: 'help4unotification.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDxtJbbOmNIKKnN_7jsMrxfA5sWv8UXZk',
    appId: '1:890970742539:web:0eca799734963a97b24c0e',
    messagingSenderId: '890970742539',
    projectId: 'help4unotification',
    authDomain: 'help4unotification.firebaseapp.com',
    storageBucket: 'help4unotification.firebasestorage.app',
    measurementId: 'G-QYFJHRRLEC',
  );
}
