// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqzaHv96uA9ldCY9nfxw_Vi_obEHpoUg',
    appId: '1:587161604739:web:3af65b490abd887061c1b6',
    messagingSenderId: '587161604739',
    projectId: 'help4ulatest',
    authDomain: 'help4ulatest.firebaseapp.com',
    storageBucket: 'help4ulatest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNT5lf96CUUUZ-NNS8ilyEP98TXCe8QQ',
    appId: '1:587161604739:android:bc7c57b9d4c8f4fe61c1b6',
    messagingSenderId: '587161604739',
    projectId: 'help4ulatest',
    storageBucket: 'help4ulatest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwTSJS2a1VKF_wV80kFwqlvTpBnH75FaQ',
    appId: '1:587161604739:ios:8960322cf3edf66761c1b6',
    messagingSenderId: '587161604739',
    projectId: 'help4ulatest',
    storageBucket: 'help4ulatest.firebasestorage.app',
    iosBundleId: 'tarc.edui.my.workshopAssignment',
  );
}
